### ISSUE TITLE
End of sprint bug list

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/sleuth-coop#107]
## Things we might be able to do / bugs that need fixing:

**Compulsory** (to fix before MVP goes out)
- [x] File download fix or remove file upload functionality (except for logo) **Jessie & Joe**
- [x] Logo broken link fix (ternary change?) **Emma**
- [x] Ensure README.md has all necessary information for setting up local dev environment (missing the `SECRET` key currently?)
- [ ] Stop overwriting logo (and other files?) if user edits profile but doesn't upload new files/logo #117 
- [ ] Get user's company ID, rather than relying on the User ID and Company ID matching up #124
- [ ] More in-depth security "audit" and confirmation of limitations, improvements, etc with Hilary

**Ideally to be done**
- [x] Add margin or something to below "add link" section
- [x] "Confirm password" functionality on signup carousel **Dom**
- [ ] Log out functionality #120 
- [ ] File size and type limit for uploads #119 

**Nice to have**
- [ ] Timeout/something to limit carousel glitch on fast clicks #65 
- [ ] Account deletion, password update, etc (future sprints...) #123 #122 #121 #120 
- [ ] Use paid Heroku plan, so site doesn't "sleep" (significantly improve load times for visitors if traffic volumes are low) - this would be done by Hilary/Sleuth
- [ ] Autocomplete fix: make login form work on first click when autofilled e.g. by password tool
- [ ] Enforce https redirect (i.e. if someone tries to visit the non-https version, get redirected - [possibly useful tutorial](https://medium.com/@seunghunsunmoonlee/how-to-enforce-https-redirect-http-to-https-on-heroku-deployed-apps-a87a653ba61e)) - requires paid Heroku plan

**Checks**
- [ ] GDPR compliance check required? 
- [ ] Cookie notice required? (don't think so, as they're not third party)

**Comment by VirtualDOMinic** [comment]
Probably need to look into GDPR compliance and account deletion, too

**Comment by VirtualDOMinic** [comment]
Have updated the list in the top comment on this issue with a few more items
